[workspace]
members = [
  "proto-types",
  "proto-messages",
  "gears",
  "trees",
  "database",
  "tendermint",
  "gaia-rs",
  "store",
  "x/bank",
  "x/auth",
  "keyring",
]
resolver="2"

[workspace.dependencies]
prost = { version = "0.11" }
axum = "0.6.18"