[workspace]
members = ["proto-types", "proto-messages", "app", "trees"]

[patch.crates-io]
prost = { git = 'https://github.com/joneskm/prosit' }
prost-derive = { git = 'https://github.com/joneskm/prosit' }
prost-types = { git = 'https://github.com/joneskm/prosit' }
