[workspace]
members = [
  "proto-types",
  "proto-messages",
  "gears",
  "gears-derive",
  "trees",
  "database",
  "tendermint",
  "gaia-rs",
  "store",
  "x/bank",
  "x/auth",
  "keyring",
]
resolver = "2"

[workspace.dependencies]
thiserror = "1.0.13"
bytes = "1.2.1"
prost = { version = "0.12.3" }
axum = "0.6.18"
anyhow = "1.0.70"