[workspace]
members = [
  "proto-types",
  "proto-messages",
  "gears",
  "gears-derive",
  "trees",
  "database",
  "tendermint",
  "gaia-rs",
  "store",
  "x/bank",
  "x/auth",
  "keyring", 
  "x/ibc", 
  "utils",
]
resolver = "2"

[workspace.dependencies]

# nutype
bytes = "1.2.1"

# serialization
prost = { version = "0.12.3" }

# cashing/encryption
sha2 = "0.10.6"
bip32 = "0.5.1"
k256 = { version = "0.13.1" }
pkcs8 = { version = "0.10.2" }

# utils
anyhow = "1.0.70"
log = "0.4.21"
thiserror = "1.0.13"
clap = {version = "4.2.2", features = ["derive"]}
strum = {version = "0.26.2", features = ["derive"]}

# networking
axum = "0.7.4"
tower-http = {version = "0.5.2", features = ["cors"]}

[workspace.lints.clippy]
unused_async = "deny"
# large_enum_variant = "deny"