[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
#local
tendermint = {path = "../../tendermint"}
gears = { path = "../../gears" }
store = { path = "../../store" }
database = { path = "../../database" }
proto-types = { path = "../../proto-types" }
proto-messages = { path = "../../proto-messages" }
utils = { path = "../../utils" }
auth = { path = "../auth" }

#newtypes
bnum = {version = "0.10.0", features = ["serde"]}
bytes = { workspace = true }

#utils
clap = { version = "4.2.2", features = ["derive"] }
anyhow = { workspace = true }
strum = "0.25.0"

#serialization
serde = { version = "1.0", default-features = false }
serde_json = "1.0.93"
prost = { workspace = true }

#other
cosmwasm-std = "1.1.5"
tokio = "1.27.0"
axum = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
run_script = "0.10.1"
assert_fs = "1.1.1"
thiserror = { workspace = true }