[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
gears = { path = "../../gears" }
store = { path = "../../store" }
database = { path = "../../database" }
proto-types = { path = "../../proto-types" }
proto-messages = { path = "../../proto-messages" }
ibc-proto = { git = "https://github.com/joneskm/ibc-proto-rs" }
bytes = "1.2.1"
serde = { version = "1.0", default-features = false }
#params-module = { package = "params", path = "../params" }
cosmwasm-std = "1.1.5"
tendermint-informal = { package = "tendermint", git = "https://github.com/joneskm/tendermint-rs" }
auth = { path = "../auth" }

[dev-dependencies]
hex = "0.4.3"
