[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
tendermint = {path = "../../tendermint"}
gears = { path = "../../gears" }
store = { path = "../../store" }
database = { path = "../../database" }
proto-types = { path = "../../proto-types" }
proto-messages = { path = "../../proto-messages" }

bytes = "1.2.1"
serde = { version = "1.0", default-features = false }
#params-module = { package = "params", path = "../params" }
cosmwasm-std = "1.1.5"
auth = { path = "../auth" }
anyhow = "1.0.70"
clap = { version = "4.2.2", features = ["derive"] }
tokio = "1.27.0"
serde_json = "1.0.93"
prost = { version = "0.11" }
strum = "0.24.1"
axum = "0.6.18"
bnum = {version = "0.10.0", features = ["serde"]}

[dev-dependencies]
hex = "0.4.3"
