[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
#local
# tendermint = {path = "../../tendermint"}
gears = { path = "../../gears" }
# store = { path = "../../store" }
# database = { path = "../../database" }
# proto-types = { path = "../../proto-types" }
# proto-messages = { path = "../../proto-messages" }
auth = { path = "../auth" } # TODO:NOW REMOVE

#newtypes
bnum = { workspace = true, features = ["serde"] }
bytes = { workspace = true }

#utils
clap = { workspace = true }
anyhow = { workspace = true }
strum = { workspace = true }

#serialization
serde = { workspace = true, default-features = false }
serde_json = { workspace = true }
prost = { workspace = true }

#other
tokio = { workspace = true }
axum = { workspace = true }

[dev-dependencies]
hex = { workspace = true }