[package]
edition = "2021"
name = "auth"
version = "0.1.0"

[dependencies]
#local
database = {path = "../../database"}
gears = {path = "../../gears"}
proto-messages = {path = "../../proto-messages"}
proto-types = {path = "../../proto-types"}
store = {path = "../../store"}
tendermint = {path = "../../tendermint"}

#newtypes
bnum = {version = "0.10.0", features = ["serde"]}
bytes = {workspace = true}
num-bigint = {version = "0.4.4", features = []}
num-format = {version = "0.4.4", features = ["with-num-bigint"]}
num-traits = "0.2.17"
secp256k1 = {version = "0.28.1", features = ["hashes"]}

#utils
anyhow = {workspace = true} 
clap = { workspace = true }
data-encoding = "2.4.0" #replace hex with this crate
hex = "0.4.3" 
regex = "1.10.2" 
sha2 = { workspace = true }
thiserror = {workspace = true} 

#serialization
ciborium = "0.2.1"
prost = {workspace = true}
serde = {version = "1.0", default-features = false}
serde_json = "1.0.93"

#other
tokio = "1.27.0"

[dev-dependencies]
rand = "0.8.5"
strum = {workspace = true}
