[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
#local
tendermint = {path = "../../tendermint"}
gears = { path = "../../gears" }
store = { path = "../../store" }
database = { path = "../../database" }
proto-types = { path = "../../proto-types" }
proto-messages = { path = "../../proto-messages" }

#newtypes
bytes = { workspace = true }
num-format = { version = "0.4.4", features = ["with-num-bigint"]}
num-bigint = { version = "0.4.4", features = [ ]}
bnum = {version = "0.10.0", features = ["serde"]}
num-traits = "0.2.17"

#utils
anyhow = { workspace = true }
clap = { version = "4.2.2", features = ["derive"] }
once_cell = "1.18.0"
thiserror = { workspace = true }
sha2 = "0.10.8"
hex = "0.4.3"
regex = "1.10.2"
data-encoding = "2.4.0" #replace hex with this crate

#serialization
prost = { workspace = true }
serde = { version = "1.0", default-features = false }
serde_json = "1.0.93"

#other
tokio = "1.27.0"

[dev-dependencies]
rand = "0.8.5"
strum = { version = "0.25", features = ["derive"] }
secp256k1 = { version = "0.25.0", features = ["bitcoin-hashes", "rand", "global-context"] } # for tests we need rand feature