[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.13"
trees = { path = "../trees" }
database = { path = "../database" }
integer-encoding = "3.0.4"
sha2 = "0.10.6"
strum = "0.24.1"
strum_macros = "0.24"

[dev-dependencies]
hex = "0.4.3"
