[package]
name = "trees"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.13"
sha2 = "0.10.6"
integer-encoding = "3.0.4"
database = { path = "../database" }

[dev-dependencies]
hex = "0.4.3"
criterion = "0.5.1"
rand = "0.8.5"
pprof = { version = "0.12", features = ["flamegraph", "criterion"] }

[[bench]]
name = "iavl_benchmark"
harness = false
