[package]
edition = "2021"
name = "keyring"
version = "0.1.0"

[dependencies]
#local
proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}

#newtypes

#utils
argon2 = {version = "0.5.2", features = ["std"]}
ripemd = "0.1.3"
rpassword = "7.2.0"
sha2 = { workspace = true }
thiserror = { workspace = true }

#serialization

#other
bip32 = "0.5.1"
k256 = { workspace = true, features = ["ecdsa", "ecdsa-core", "pkcs8", "pem"] }
pkcs8 = { workspace = true, features = ["pem", "alloc", "std", "encryption"]}


[dev-dependencies]
