[package]
edition = "2021"
name = "keyring"
version = "0.1.0"

[dependencies]
argon2 = {version = "0.5.2", features = ["std"]}
bip32 = "0.5.1"
k256 = {version = "0.13.1", features = ["ecdsa", "ecdsa-core", "pkcs8", "pem"]}
keyring = "2.0.5"
pkcs8 = {version = "0.10.2", features = ["pem", "alloc", "std", "encryption"]}
proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}
ripemd = "0.1.3"
rpassword = "7.2.0"
sha2 = "0.10.6"
thiserror = "1.0.48"

[dev-dependencies]
