[package]
edition = "2021"
name = "keyring"
version = "0.1.0"

[dependencies]
#local
proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}
tendermint = {path = "../tendermint", features = ["proto"]}

#newtypes

#utils
argon2 = {workspace = true, features = ["std"]}
ripemd = {workspace = true}
rpassword = {workspace = true}
sha2 = {workspace = true}
thiserror = {workspace = true}

#serialization
hex = {workspace = true, features = ["serde"]}
serde = {workspace = true}
serde_json = {workspace = true}

#other
bip32 = {workspace = true}
k256 = {workspace = true, features = ["ecdsa", "ecdsa-core", "pkcs8", "pem"]}
pkcs8 = {workspace = true, features = ["pem", "alloc", "std", "encryption"]}

[dev-dependencies]
