[package]
edition = "2021"
name = "proto-messages"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
base64-serde = "0.7.0"
cosmwasm-std = "1.1.5"
ibc-proto = {workspace = true}
prost = "0.11.8"
proto-types = {path = "../proto-types"}
ripemd = "0.1.3"
serde = {version = "1.0", default-features = false}
serde-aux = "4.2.0"
serde_with = "3.0.0"
sha2 = "0.10.6"
tendermint-informal = {package = "tendermint", git = "https://github.com/joneskm/tendermint-rs"}
thiserror = "1.0.13"
secp256k1 = { version = "0.25.0", features = ["bitcoin-hashes"] }
nutype = { version = "0.3.1" , features = [ "serde"]}
byteorder = "1.5.0"
micromarshal = "0.4.1"
ciborium = "0.2.1"
bnum = {version = "0.10.0", features = ["serde"]}
num-traits = "0.2.17"

[dev-dependencies]
hex = "0.4.3"
serde_json = "1.0.93"
data-encoding = "2.4.0"
