[package]
name = "proto-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.11.8"
ibc-proto = "0.26.0"
proto-types = { path = "../proto-types" }
cosmwasm-std = "1.1.5"
thiserror = "1.0.13"
sha2 = "0.10.6"
ripemd = "0.1.3"
serde = { version = "1.0", default-features = false }
serde-aux = "4.2.0"

[dev-dependencies]
hex = "0.4.3"
