[package]
edition = "2021"
name = "proto-messages"
version = "0.1.0"

[dependencies]
base64 = "0.21.0"
base64-serde = "0.7.0"
cosmwasm-std = "1.1.5"
ibc-proto = {workspace = true}
prost = "0.11.8"
proto-types = {path = "../proto-types"}
ripemd = "0.1.3"
secp256k1 = {workspace = true}
serde = {version = "1.0", default-features = false}
serde-aux = "4.2.0"
serde_with = "3.0.0"
sha2 = "0.10.6"
tendermint-informal = {package = "tendermint", git = "https://github.com/joneskm/tendermint-rs"}
thiserror = "1.0.13"

[dev-dependencies]
hex = "0.4.3"
serde_json = "1.0.93"
