[package]
name = "gov"
version = "0.1.0"
edition = "2021"

[dependencies]
gears = { path = "../../gears", features = ["cli", "export", "xmods"] }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
