[package]
name = "gaia-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
proto-types = { path = "../proto-types" }
proto-messages = { path = "../proto-messages" }
cosmwasm-std = "1.1.5"
ibc-proto = { git = "https://github.com/joneskm/ibc-proto-rs" }
tendermint-proto = { git = "https://github.com/joneskm/tendermint-rs" }
clap = { version = "4.2.2", features = ["derive"] }
bytes = "1.2.1"
serde = { version = "1.0", default-features = false }
database = { path = "../database" }
anyhow = "1.0.70"
gears = { path = "../gears" }
store = { path = "../store" }
strum = "0.24.1"
strum_macros = "0.24"
bank = { path = "../x/bank" }
auth = { path = "../x/auth" }
axum = "0.6.18"

[dev-dependencies]
