[package]
edition = "2021"
name = "gaia-rs"
version = "0.1.0"

[dependencies]
anyhow = "1.0.70"
auth = {path = "../x/auth"}
axum = "0.6.18"
bank = {path = "../x/bank"}
bytes = "1.2.1"
clap = {version = "4.2.2", features = ["derive"]}
cosmwasm-std = "1.1.5"
database = {path = "../database"}
gears = {path = "../gears"}
proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}
serde = {version = "1.0", default-features = false}
store = {path = "../store"}
strum = { version = "0.25", features = ["derive"] }
tendermint-informal = {package = "tendermint", git = "https://github.com/joneskm/tendermint-rs"}
tendermint-proto = {git = "https://github.com/joneskm/tendermint-rs"}

[dev-dependencies]
