[package]
edition = "2021"
name = "gears"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
#local
tendermint = {path = "../tendermint"}
# proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}
keyring = {path = "../keyring"}
database = {path = "../database"}
store_crate = {path = "../store", package = "store"}
trees = {path = "../trees"}

#newtypes
secp256k1 = { workspace = true, features = ["hashes"]}
bytes = { workspace = true }
url = { workspace = true }

#utils
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
integer-encoding = { workspace = true }
sha2 = { workspace = true }

#serialization
prost = { workspace = true }
bech32 = { workspace = true }
hex = { workspace = true }
serde = { workspace = true, default-features = false}
serde-aux = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }

#other
dirs = { workspace = true }
bip32 = { workspace = true }
handlebars = { workspace = true }
human-panic = "1.1.4"
strum = { workspace = true }
text_io = "0.1.12"
tokio = { workspace = true, features = [ "rt", "rt-multi-thread"] }
derive_builder = { workspace = true }

# networking
axum = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }

#cli
clap = { workspace = true , optional = true }
clap_complete = { workspace = true, optional = true }

[dev-dependencies]

[features]
default = [ "cli" ]
cli = [ "dep:clap", "dep:clap_complete", ]