[package]
edition = "2021"
name = "gears"
version = "0.1.0"

[dependencies]
#local
tendermint = {path = "../tendermint", features = [ "rpc", "abci", "proto" ]}
proto-messages = {path = "../proto-messages"}
proto-types = {path = "../proto-types"}
keyring = {path = "../keyring"}
database = {path = "../database"}
store_crate = {path = "../store", package = "store"}
trees = {path = "../trees"}

#newtypes
secp256k1 = {version = "0.28.1", features = ["hashes"]}
bytes = { workspace = true }

#utils
rand = "0.8.5"
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = {version = "0.1", default-features = false}
tracing-subscriber = {version = "0.3.18", optional = false, default-features = true}
clap = {version = "4.2.2", features = ["derive"]}
clap_complete = "4.2.1"
integer-encoding = "4.0.0"
lazy_static = "1.4.0" # TODO: replace with once_cell from std or crate
sha2 = "0.10.6"
log = { workspace = true }

#serialization
prost = { workspace = true }
bech32 = "0.9.1"
hex = "0.4.3"
serde = {version = "1.0", default-features = false}
serde-aux = "4.2.0"
serde_json = "1.0.93"
toml = "0.8.8"

#other
dirs = "5.0.1"
bip32 = "0.5.1"
cosmwasm-std = "1.1.5"
axum = { workspace = true }
handlebars = "5.1.0"
human-panic = "1.1.4"
strum = { version = "0.25", features = [] } # "derive"
text_io = "0.1.12"
tokio = "1.27.0"
tower-http = {version = "0.4.1", features = ["cors"]}
derive_builder = "0.20.0"

[dev-dependencies]

[features]
default = [ "cli"]
cli = []