name: Run tests

on:
  # Run on any PR
  pull_request:
    

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
    - name: Checkout  # Clone git repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y llvm clang libclang-dev build-essential libhidapi-dev

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Execute tests
      run: cargo test --features=it  --no-fail-fast 